version: '3.1'

services:
  luna-nginx:
    container_name: luna-nginx
    image: nginx:1.13
    restart: always
    ports:
      - 8082:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app

  database:
    image: mysql:8.0.22
    restart: always
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mysql
      - MYSQL_USER=myapp-user
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 30s
      retries: 3
  app:
    depends_on:
      database:
        condition: service_healthy
    build: .
    ports:
      - 8081:8081
#    command: mvn clean spring-boot:run
    environment:
      - DATABASE_HOST=myapp-mysql
      - DATABASE_USER=myapp-user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=mysql
      - DATABASE_PORT=3306
